version: '3.8'

services:
  todo-frontend:
    container_name: todo-frontend
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge